version: '3'

volumes:
  local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    entrypoint: ['/usr/src/app/compose/local/django/entrypoint.sh']
    image: ecommerce
    depends_on:
      - django-db
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"


  django-db:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: ecommerce_postgres
    expose:
      - 5432    
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres